version: "3.8"

services:
  app:
    container_name: "${PROJECT_NAME}-php"
    build: ./Docker
    volumes:
      - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html
      - "~/.gitconfig:/etc/gitconfig"
    ports:
      - "80:80"

  db:
    container_name: "${PROJECT_NAME}-mariadb"
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ${PATH_TO_DB_DATA}:/var/lib/mysql:rw
    ports:
      - "3306:3306"
