version: "3.8"

services:
  frontend:
    container_name: "${PROJECT_NAME}-node"
    build: ./project/frontend
    volumes:
      - ./project/frontend/app:/app
    ports:
      - "5173:5173"

  backend:
    container_name: "${PROJECT_NAME}-php"
    build: ./project/backend
    volumes:
      - ./project/backend/app:/var/www/html
    ports:
      - "80:80"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: "${PROJECT_NAME}-mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"

  db:
    image: mariadb:latest
    container_name: "${PROJECT_NAME}-mariadb"
    restart: always
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - ${PATH_TO_DB_DATA}:/var/lib/mysql:rw

  adminer:
    image: adminer:latest
    container_name: "${PROJECT_NAME}-adminer"
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=db
    ports:
      - 8080:8080